Algoritmo "Exercicio 15"
// 

Var
// Seção de Declarações das variáveis 
contador, n, soma, x: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contador <- 1
soma <- 1
x <- 0
escreva("quantas vezes: ")
leia (n)
enquanto contador <= n faca
Escreva (soma)
contador <- contador + 1
x <- soma + x
soma <- 1/contador

fimenquanto

Escreva (" a soma de todos é:", x )
Fimalgoritmo