Algoritmo "EXERCICIO 13"
// 

Var
// Seção de Declarações das variáveis 
contador,tres ,cinco,vezes, n : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contador <- 1
Escreva ("quantas vezes você quer que repita? ")
leia (vezes)
enquanto contador <= vezes faca
escreva ("informe o número desejado: ")
leia (n)
tres <- n * 3
cinco <- n * 5
Escreval (n," x 3 =", tres, "  e  ", n, " x 5 =", cinco)
contador <- contador + 1
fimenquanto



Fimalgoritmo