Algoritmo "Exercicio 4"
// 

Var
// Seção de Declarações das variáveis 
Contador, x : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Contador <- 101
x <- 0
Enquanto contador <= 200 faca

se contador % 2 <> 0 entao
x <- x + 1
escreva (contador)
fimse

contador <- contador + 1
fimenquanto

escreval ("")

Escreva (" possuem", x," números impares")
escreval ("")
Fimalgoritmo