Algoritmo "EXERCICIO 12"
// 

Var
// Seção de Declarações das variáveis 
contador, n, maior, menor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contador <- 1
enquanto contador <= 10 faca
Escreval (" informe 10 nùmeros")
Leia (n)

se n > maior entao
maior <- n
senao n < menor
menor <- n

fimse
contador <- contador + 1
fimenquanto


escreva (" o maior número é :", maior)
escreva (" o menor número é :", menor)
Fimalgoritmo