Algoritmo "EXERCICIO 6"
// 

Var
// Seção de Declarações das variáveis 
idade, ano, t: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Quantos anos você tem?")
leia (idade)
Escreval ("Em que ano estamos?")
leia (ano)
Escreval ("Uma informação que não vai somar nada na sua vida,")
Escreval ("mas quer saber com quantos anos vai ter em 2028???")

t <- idade + (2028 - ano)

Escreva ("-----------Você terá", t," anos de idade-----------")

Fimalgoritmo