Algoritmo "EXERCICIO 5"
// 

Var
// Seção de Declarações das variáveis 
produto, p: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("BEM VINDO!!, estamos com uma nova promoção, informe o valor do")
Escreval ("produto e iremos descontar o valor de 5%")

Leia (produto)

    p <- (produto) - (produto*(5/100))
Escreval ("")
Escreva ("o produto ficou em", p," reais")
Escreval ("")
Fimalgoritmo